### ISSUE TITLE
Predicate-versions of unexpandable macros

### ISSUE THREAD

**Issue by Skillmon** [alceu-frigeri/starray#1] opened 2023-05-15 18:22 UTC
The package defines predicate versions of boolean-functions for unexpandable functions (e.g. `\starray_new:n` and `\starray_new_p:n`). These can't work as intended, a predicate must always be fully expandable in `expl3`:

```latex
\documentclass{article}

\usepackage{starray}

\ExplSyntaxOn
\bool_if:nTF { \starray_new_p:n {myfoo} }
  { \message { TRUE } }
  { \message { FALSE } }

\bool_if:nTF { \starray_new_p:n {myfoo} }
  { \message { TRUE } }
  { \message { FALSE } }
\ExplSyntaxOff

\stop
```

throws a low-level TeX error because of a missing number.

**Comment by alceu-frigeri** [comment] 2023-05-15 18:43
protected / non-protected ... yep, you are right... and "I had a note to myself" to go over the code and see what needed to be protected or not (and... sorry... I forgot about it).
"to be fixed" (as soon as possible).
predicates (funny, not so funny: I only defined them because of a bug/feature in expl3, you have to have all variants defined otherwise _generate_variant: will miss-behave)

**Comment by Skillmon** [comment] 2023-05-15 18:53
> you have to have all variants defined otherwise _generate_variant: will miss-behave)

Do you mean https://github.com/latex3/latex3/issues/1189? I don't think it would affect you...

**Comment by alceu-frigeri** [comment] 2023-05-15 18:59
yep, it was this one... and another (I would have to search for it again... it was related to  \cs_generate_variant ).
per-se, in my intended use case/cases... the predicated version is moot, but, sure, others will beg to differ. ;)

**Comment by alceu-frigeri** [comment] 2023-05-15 20:49
OK. I did a 'dry run', replacing all \cs_new by \cs_new_protected, and things go really wrong (I have a test file and it won't compile, seems like a \quark loop of sorts). I will have to investigate it further. 
Btw,  trying to set 'at least' the _conditional_ ones as protected (\prg_new_protected_conditional) and the kernel complains "it can't protect those" (... code had to be expandable in the first place... which runs a fool of the issue).
Edit: as said, I have to look into it (if there is a way) . . . otherwise might be a 'bug'/'feature' :(

**Comment by alceu-frigeri** [comment] 2023-05-15 21:26
As said, it's more complicated than it looks at first. For instance:
```latex
\ExplSyntaxOn

\prg_new_protected_conditional:Npnn \__starray_if_free:n #1 {T, F, TF}
  {
    \prop_if_exist:cTF {#1}
      { \prg_return_false: }
      { \prg_return_true: }
  }

\prg_generate_conditional_variant:Nnn \__starray_if_free:n {e} {T, F, TF}

\prg_new_protected_conditional:Npnn \starray_new:n #1 {T, F, TF}
  {
    \__starray_if_free:nTF {\l__starray_prefix_tl #1 _def_prop}
      {
%        \__starray_new:e {#1 }
%        \__starray_base_new:ee {#1}{#1} % TODO: might be incomplete !!!
        \prg_return_true:
      }
      { \prg_return_false: }
  }

\ExplSyntaxOff
```

```\prop_if_exist:``` is expandable (per interface3.pdf), so 'this' above should be a clear cut, but, if I try:
```latex
\prg_new_protected_conditional:Npnn \__starray_if_free:n #1 {p, T, F, TF}
```
it complains right away that the code should be expandable and abort the job.

I will investigate it further. Meanwhile, I will open an issue in stackexchange (:lol:) and (perhaps) latex3 (here, github) too.

EDIT: 
https://tex.stackexchange.com/questions/685809/generating-protected-expandable-predicates-in-expl3
and
https://github.com/latex3/latex3/issues/1202

**Comment by alceu-frigeri** [comment] 2023-05-16 00:20
OK... the 'not so good' answer.
From https://github.com/latex3/latex3/issues/1202 
\prog_new_protected_conditional ... can't be used to define a predicate one (only T, F and TF).
\prog_new_conditional can, but, the predicate one (meaning, all the code) has to be fully expandable... which, in my case, isn't (because of the use of many non-expandable functions from expl3 :/ )

so, the way to 'solve this' is just, unfortunately, to remove the predicate definitions and add a remark (on the documentation) the most/all defined commands aren't expandable...

(I will try to further test it, to see if at least, 'part of if' could be marked as expandable...)

EDIT:
Of all defined functions, all but one can, at least, be protected... though the one that can't is just:
 ```\cs_new:Npn \__starray_get_root:w #1 . #2 \q_stop { #1 }```
 which is used extensively (I mean, in many cases, I avoid using my internal parser and use this shortcut to get the 'root' of a starray-ref ... and, back to square one: my code, mostly, isn't expandable... :/
 so, the solution, more and more, seems to make people aware that "those functions aren't expandable", there is no predicate variant of the conditionals...
 
 EDIT2: and yeah, this is the function that, when 'protected' results in a quark loop... just confirmed it.

**Comment by alceu-frigeri** [comment] 2023-05-16 11:39
I got some time to review a bit of the code, and, 'nothing much to be done', except 'protecting' almost them all and recording that on the documentation.
all ```\starray_``` commands rely on ```\__starray_parser``` which isn't expandable (```\tl_clear```). So, basically this is it.

@Skillmon thanks for the notice. I will be closing this once I submit a new version at CTAN.

**Comment by alceu-frigeri** [comment] 2023-05-16 18:20
closing it. 'corrected' version submitted to ctan.

**Closed as completed by alceu-frigeri** 2023-05-16 18:20 UTC
Labels: working on, escalating it, feature/bug
